# Generated by Django 3.2.7 on 2021-09-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lappyng_app.products'),
        ),
    ]
