# Generated by Django 3.2.7 on 2021-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0002_alter_productrequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(choices=[('10', 1), ('20', 2), ('30', 3), ('40', 4), ('50', 5), ('60', 6), ('70', 7), ('80', 8), ('90', 9), ('100', 10), ('', 'Choose Rating')], default='', max_length=10),
        ),
    ]
