# Generated by Django 3.2.7 on 2021-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0002_remove_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Old Price'),
            preserve_default=False,
        ),
    ]
