# Generated by Django 3.2.7 on 2021-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0003_products_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Slide Image')),
                ('slide_content1', models.TextField(blank=True, null=True)),
                ('slide_content2', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '7. Banner',
            },
        ),
    ]
