# Generated by Django 3.2.7 on 2021-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0003_alter_productreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='old_price',
        ),
        migrations.AddField(
            model_name='products',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Example 30%', max_digits=3, null=True, verbose_name='Percentage Discount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
    ]
