# Generated by Django 3.2.7 on 2021-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0004_auto_20210930_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percent',
            field=models.PositiveBigIntegerField(blank=True, help_text='Example 30%', null=True, verbose_name='Percentage Discount'),
        ),
    ]
