# Generated by Django 3.2.7 on 2021-09-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hot_deal',
            field=models.BooleanField(default=1, verbose_name='Hot Deals of this Week'),
            preserve_default=False,
        ),
    ]
