# Generated by Django 3.2.7 on 2021-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percent',
            field=models.PositiveIntegerField(blank=True, help_text='Example 30%', null=True, verbose_name='Percentage Discount'),
        ),
    ]
