# Generated by Django 3.2.7 on 2021-09-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0006_auto_20210909_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='imagess1',
        ),
    ]
