# Generated by Django 3.2.7 on 2021-09-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0007_rename_image1_products_imagess1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imagess1',
            new_name='image1',
        ),
    ]
