# Generated by Django 3.2.7 on 2021-09-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0008_rename_imagess1_products_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
