# Generated by Django 3.2.7 on 2021-10-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0009_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
