# Generated by Django 3.2.7 on 2021-10-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0010_auto_20211002_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Home Slider'},
        ),
    ]
