# Generated by Django 3.2.7 on 2021-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0010_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='popular',
            field=models.BooleanField(default=1, verbose_name='Popular Post'),
            preserve_default=False,
        ),
    ]
