# Generated by Django 3.2.7 on 2021-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0012_products_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img_banner2',
            field=models.ImageField(blank=True, help_text='Use this Image dimension 848px X 132px', null=True, upload_to='uploads/', verbose_name='Category Banner Image'),
        ),
    ]
