# Generated by Django 3.2.7 on 2021-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0014_auto_20211003_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSideBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='uploads/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home Side Banner',
            },
        ),
    ]
