# Generated by Django 3.2.7 on 2021-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0015_homesidebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometopbanner',
            old_name='banner',
            new_name='banner1',
        ),
        migrations.RenameField(
            model_name='hometopbanner',
            old_name='link',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='hometopbanner',
            name='banner2',
            field=models.ImageField(default='rr', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometopbanner',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
