# Generated by Django 3.2.7 on 2021-09-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0015_auto_20210921_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='new',
        ),
    ]
