# Generated by Django 3.2.7 on 2021-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0017_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
