# Generated by Django 3.2.7 on 2021-11-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0018_auto_20211104_0700'),
        ('lappyng_app', '0018_auto_20211105_0324'),
    ]

    operations = [
    ]
