# Generated by Django 3.2.7 on 2021-11-07 16:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0021_pages_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=16, null=True)),
                ('phone2', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='slide_img',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload A Banner of 870px X 530px', max_length=255, null=True, verbose_name='Slide Image'),
        ),
        migrations.AlterField(
            model_name='homesidebanner',
            name='banner',
            field=cloudinary.models.CloudinaryField(help_text='Upload A Banner of 270px X 285px', max_length=255),
        ),
        migrations.AlterField(
            model_name='hometopbanner',
            name='banner',
            field=cloudinary.models.CloudinaryField(help_text='Upload A Banner Of 870px X 200px', max_length=255),
        ),
        migrations.AlterField(
            model_name='hometwosidebanner',
            name='banner',
            field=cloudinary.models.CloudinaryField(help_text='Upload A Banner of 570px X 200px', max_length=255),
        ),
    ]
