# Generated by Django 3.2.7 on 2021-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappyng_app', '0022_auto_20211107_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_img_banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_img_banner2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
